title: Py Campers
ga_analytics: UA-119542427-2
remote_theme: nielsenramon/chalk
blog_theme: dark
name: Py Campers
paginate: 25
url: http://pycampers.com/
social:
    github: https://github.com/pycampers
    twitter: https://twitter.com/pycampers
    youtube: https://www.youtube.com/channel/UCgCeAEPuLidDCKJKMZO2eGA
    email: pycampers@gmail.com
